name: "CI/CD Pipeline - Build and Push"
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: "Stage 1: Checkout Code"
        uses: actions/checkout@v4
        
      - name: "Stage 2: Log in to DockerHub"
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          
      - name: "Stage 3: Build Docker Image"
        working-directory: pipeline-practice
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ris-devops-practice-project:latest .
        
      - name: "Stage 4: Tag Docker Image with Commit SHA"
        working-directory: pipeline-practice
        run: |
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/ris-devops-practice-project:latest ${{ secrets.DOCKERHUB_USERNAME }}/ris-devops-practice-project:$COMMIT_SHA
          
      - name: "Stage 5: Push Docker Images to DockerHub"
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ris-devops-practice-project:latest
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ris-devops-practice-project:$COMMIT_SHA
